### ISSUE TITLE
Probing devRant API (ts-devrant/RantScript)

### ISSUE THREAD

**Issue by vintprox** [anjannair/Devrant-Discord-Bot#3]
One good JS library for surfacing devRant API would be RantScript. But there is also TypeScript version of that I recommend to check out: https://www.npmjs.com/package/ts-devrant

Blocker: currently determined lack of TypeScript support.

## What is expected?

Minimal command with the usage of devRant API.

## Implementation

Make new command for displaying completely random rant. Try out [devRant.surpriseRant](https://github.com/dr010001111/ts-devrant/blob/3581c23600acf459da3401abc734f5f45a4f35a3/src/api.ts#L239) call, display the author, text of received rant and URL to it.

**Comment by anjannair** [comment]
Already using the proper devRant API without a package. Closing this for now. You can open it if not solved!
