### ISSUE TITLE
Fetch random Q&A from Hashnode AMA?

### ISSUE THREAD

**Issue by vintprox** [anjannair/Devrant-Discord-Bot#5]
I find AMA category on Hashnode quite inspirational with all these questions and answers. [Example.](https://hashnode.com/post/i-have-helped-over-60-people-land-their-first-jobs-in-tech-i-am-danny-thompson-ama-ckduno8900004bns1a5ce50sq)

Can we fetch random pair of questions and answers using Hashnode's GraphQL API? Awaiting response here: https://engineering.hashnode.com/introducing-hashnode-graphql-api-public-beta-cjydzvp59001q2gs1b5zxaeaf#ckgzlwc9g04bt20s15vxablx2

One thing for sure: integrating something from Hashnode won't be much of a hassle, since the API is well tested and you can access it with **curl**.

**Comment by vintprox** [comment]
https://engineering.hashnode.com/announcement-breaking-changes-graphql-api-cjysoieg40002yps1xjj9wwb5

Access to AMAs is veeery straightforward in latest API. Piece of cake:
- take random AMA,
- pick random question from it,
- grab replies from that question.

**Comment by anjannair** [comment]
Will start working on it soon!

**Comment by anjannair** [comment]
> One thing for sure: integrating something from Hashnode won't be much of a hassle, since the API is well tested and you can access it with **curl**.
Why not just stick with **node-fetch** itself? The API can easily be accessed via that.

**Comment by vintprox** [comment]
I, by any means, do not insist on using raw `curl`, because `node-fetch` is
basically all you need for the task.

пн, 2 Ноя 2020 г., 19:35 Anjan Nair <notifications@github.com>:

**Comment by anjannair** [comment]
The Hashnode API is still not well developed to be integrated so I'm gonna close this till that is done. If you see it's developed then do open the issue again.
