### ISSUE TITLE
Link summarizer does too much job

### ISSUE THREAD

**Issue by vintprox** [anjannair/Devrant-Discord-Bot#6]
Currently, behaviour that lets bot to parse text contents by link, without asking, is off. We would like it to **not** litter space unless somebody explicitly asks for it by saying "describe"/"parse"/"summarize".

/cc @anjannair
Cheers!

**Comment by anjannair** [comment]
Yeah cool will do!

**Comment by vintprox** [comment]
> Yeah cool will do! But I don't think then it will ever be used then 😓

Indeed, that's a dilemma: balancing between UX and feature richness was never so easy.

First thing I would try is to conduct user interviews about what improvements in Discord are needed and how they would help.

Some time ago, I was organizing the online event for members of chit-chat server. People were mostly unaware of how much their timezones matter, everyone had either specific or vague schedules, then me and they were easily confused by the amount of timezones, because it's the information that you barely keep in mind. That's when I saw the problem arise. Basically you can even play around with this idea, since it's some big brain problem solving and there is no copyright on idea 😅 (if you are interested).

**Comment by vintprox** [comment]
Alright, here's an idea: why not react with emoji to the message with link posted, then user presses it and summary appears?

**Comment by anjannair** [comment]
Fixed issue. Will be closing it now.
