### ISSUE TITLE
Timezone profiles and input

### ISSUE THREAD

**Issue by vintprox** [anjannair/Devrant-Discord-Bot#7]
## What problem does it solve?

Ensuring that manually planned events get an opportune estimated time of start, taking into account the timezones and free time periods of everyone involved. For starters, simple timezone profiles and input are enough. Free time allocation feature should reside in another issue.

## Proposed solution

Collect timezones from each user on a voluntary basis, i.e. setting it via command. We would probably be in right if we set up "**Event Manager**" role. Event manager and admins should be able to change user's timezone and even create **agent profiles** for accounting *external guests* (that for whatever reason may not attend Discord).

Basic usage of collected timezones is to know each other's time via another command (or same - it depends on "smartiness" of implementation). Maybe even print out a **time table** with some Discord magic involved in formatting.

## Recommendation for implementing timezone parser

User may be aware of exactly in which time zone they are and may be not. Please, take it into account while making this command. Command can accept either exact values or vague ones (recommended). For former, use **fuzzy** search (Levenshtein Distance algorithm).

Command should intuitively understand:
- timezones' abbreviations,
- timezones' names - and prompt to resolve any disambiguations (example: "Philippines" and "Philippine");
- countries/cities - and resolve to appropriate timezone, prompt if clash appears;
- UTC offsets (`-4`, `+3:00`, `8:30`);
- current time posted by user themself - and round it up to the most fitting UTC offset.

Remember: _offset ≠ timezone_. When possible, store timezones instead of offsets. If user chooses to sacrifice their privacy a bit and post their country, it's better to resolve it to appropriate timezone bound to this country as per IANA db and not offset. It's because offsets change over seasons in some places, and so user or manager has to update offsets, they even can lose track of it to the point when it becomes useless.

## Some links

IANA timezones database and advised libraries: https://data.iana.org/time-zones/tz-link.html

Fuzzy search library: https://glench.github.io/fuzzyset.js/

**Comment by anjannair** [comment]
@vintprox thought a lot over this and currently if you need to setup individual preferences and profiles I'll have to start relying on databases to store it. Although the time conversions can be achieved I do not think I can do the rest with the level of knowledge I have. If I do however stumble upon method to do this I will keep you updated.

**Comment by vintprox** [comment]
Most certainly, native JS will require more boilerplate code for such conversions, especially fetching timezones. As for database design, you can store on user offset and valid timezone name. Offset is the easiest variant, both are ideal.

**Comment by anjannair** [comment]
Closing this issue as Discord has this feature out of the box.

**Comment by vintprox** [comment]
> Closing this issue as Discord has this feature out of the box.

@anjannair Where? It's still a requested feature on Discord support website, that we don't have.

**Comment by anjannair** [comment]
@vintprox 
![image](https://user-images.githubusercontent.com/22571613/142764112-d3422a31-3a5b-4b24-99ea-5adb9125c2d5.png)

**Comment by vintprox** [comment]
> @vintprox ![image](https://user-images.githubusercontent.com/22571613/142764112-d3422a31-3a5b-4b24-99ea-5adb9125c2d5.png)

I suppose Events suffice this need... Thanks for pointing out
